### ISSUE TITLE
Doesn't work with FactoryGirl

### ISSUE THREAD

**Issue by calebperkins** [travisjeffery/timecop#13]
Perhaps this may be user error but I have the following factory:

``` ruby
Factory.define :auction do |f|
  f.association :product
  f.ending_at 1.hour.from_now
end
```

In a test, I then tried the following code:

``` ruby
Timecop.freeze do
  @time = 1.hour.from_now
  @auction = Factory.create :auction
end

@time # returns Sat, 01 Jan 2000 01:00:00 PST -08:00
@auction.ending_at # returns Wed, 25 May 2011 20:48:09 PDT -07:00
```

I expected the two times to be the same.

**Comment by holyketzer** [comment]
@jtrupiano Thank you man! I couldn't figure out this thing before reading you comment twice :)

**Comment by Irostovsky** [comment]
Catch the same "issue" with factory_girl and timecop. @jtrupiano, thanks a lot!
