### ISSUE TITLE
Date.parse(nil) should throw TypeError, not NoMethodError

### ISSUE THREAD

**Issue by botandrose** [travisjeffery/timecop#141]
#137 (and 0.7.2 or 0.7.3) introduced this bug. It's because nil now receives the `downcase` method in the new `Date.parse` monkeypatch, and throws a NoMethodError, where stdlib `Date.parse(nil)` will throw a TypeError.

**Comment by ThomasKoppensteiner** [comment]
@botandrose what do you think about those fixes?

**Comment by botandrose** [comment]
:+1: to either. They both address my use-case!

**Comment by ekupershtock** [comment]
DateTime.parse(nil) still throws NoMethodError
