### ISSUE TITLE
Keeping a changelog?

### ISSUE THREAD

**Issue by danielfone** [travisjeffery/timecop#143]
Hi @travisjeffery, thanks for the great work you do maintaining this gem — it's super useful!

Just wondering if you've considered keeping a changelog, perhaps like [keepachangelog.com](http://keepachangelog.com/)? I maintain a bunch of rails apps and I generally try to keep the gems up to date on all of them. In this instance I'm trying to find out the changes between 0.7.1–0.7.3 and whether there's anything that's likely to affect me. I'm guessing from the [diff](https://github.com/travisjeffery/timecop/compare/v0.7.1...master) that there's not, but it's really helpful to be able to see what the intended changes were from a maintainer's point of view

Anyway, thanks for your time!

**Comment by jeremykay** [comment]
Agreed!

**Comment by DexterTheDragon** [comment]
Same here. Would be nice to know what changes there are between 0.7.1–0.7.3.

**Comment by AaronLasseigne** [comment]
:+1:

**Comment by joshuacronemeyer** [comment]
Seems like History.md covers this now?
