### ISSUE TITLE
Behaviour when Timecop#travel receives a float

### ISSUE THREAD

**Issue by vroy** [travisjeffery/timecop#145]
I find the behaviour of a single float argument surprising:

```ruby
Timecop.freeze("2015-01-01")

puts Time.now                # => 2015-01-01 00:00:00 -0400

# 1.day => 86400
puts Timecop.travel(86400)   # => 2015-01-02 00:00:00 -0400

# 1.1.day # => 87264.0
puts Timecop.travel(87264.0) # => 87264-01-01 00:00:00 -0400
```

I use the Active Support durations extensions (`1.day`, `1.01.day`) and it some times returns a float.

Is this the expected behaviour? Would there be interest in a pull request to update the behaviour and handle a single float argument similarly to a single integer argument?

**Comment by travisjeffery** [comment]
Should be fixed now. Thanks!
