### ISSUE TITLE
Date.current, not Date.today, should be faked

### ISSUE THREAD

**Issue by btakita** [travisjeffery/timecop#148]
ActiveSupport uses `::Date.current`, not `::Date.today` as the root method to determine today, yesterday, tomorrow, etc.

Currently, timecop has inconsistencies with `::Date.yesterday` & `::Date.today`, since ActiveSupport uses `::Date.current`.

**Comment by maximeg** [comment]
`Date.current` from rails master:
```ruby
# Returns Time.zone.today when <tt>Time.zone</tt> or <tt>config.time_zone</tt> are set, otherwise just returns Date.today.
def current
  ::Time.zone ? ::Time.zone.today : ::Date.today
end
```

It's should be just fine.
Do you have a precise case of inconsistency ?

**Comment by ballcheck** [comment]
See https://github.com/travisjeffery/timecop/issues/182

Closing as duplicate
