### ISSUE TITLE
Feature: client-side time stubbing

### ISSUE THREAD

**Issue by mockdeep** [travisjeffery/timecop#152]
I ran into this need while testing a Javascript heavy application that makes use of the current date/time. In order to consistently test it with Capybara I'm going to have to use Timecop for the server, and probably just mock up my own `Date` stub using `page.evaluate_script`. It would be great if Timecop could provide something like this to make it easy to manage timers on the client side as well.

**Comment by jtrupiano** [comment]
I believe this is what you're looking for :)    https://github.com/jamesarosen/Timecop.js

**Comment by mockdeep** [comment]
Nice, I'll give that a try. Do you just include it in test mode inside one of your layouts?

**Comment by travisjeffery** [comment]
Here's a blog post that talks about using Timecop with Capybara: http://metaskills.net/2012/08/07/synchronized-times-in-ruby-and-javascript-acceptance-tests-using-capybara-timecop-and-sinon.js/.

**Comment by mockdeep** [comment]
Yeah, I came across that earlier but felt a little weird about including Sinon in my application. After thinking about it some more though I think I have enough pieces to put it all together, though. Thanks!
