### ISSUE TITLE
Does not freeze Time.now irregardless of system timezone

### ISSUE THREAD

**Issue by compwron** [travisjeffery/timecop#153]
```
Timecop.freeze(Time.utc(2014, 1, 20).to_datetime) do
 p Time.now
end
```

Behaves differently when the underlying system is in UTC vs in a different timezone (PTC for example)

**Comment by yaauie** [comment]
When opening a bug, it is helpful to *at minimum* provide three things:

 - [x] how to reproduce (specifically)
 - [ ] what you expect to happen (specifically)
 - [ ] what actually happened (specifically)

The text "behaves differently" is not sufficiently clear to demonstrate a bug, as someone needs to reproduce the bug in order to fix it.

**Comment by compwron** [comment]
Sorry about that.

````
it 'foo' do
    Timecop.freeze(Time.utc(2014, 1, 20)) do
      p Time.now
      p DateTime.now
    end
  end
# $ date
# Mon Jun 15 21:21:22 UTC 2015
# $ rspec spec/fake_spec.rb:5
# 2014-01-20 00:00:00 +0000
# Mon, 20 Jan 2014 00:00:00 +0000
 
# $ date
# Mon Jun 15 14:21:44 PDT 2015
# $ rspec spec/fake_spec.rb:5
# 2014-01-19 16:00:00 -0800
# Sun, 19 Jan 2014 16:00:00 -0700
````

I would expect the output to be the same both times.

**Comment by Sonblind** [comment]
I would use one class for consistency. `DateTime` and `Time` handle time differently, and the `Time` class may display the time without nanoseconds, but may actually store the fractional value in memory. You can read about it [here](http://ruby-doc.org/core-2.2.0/Time.html) and [here](https://robots.thoughtbot.com/its-about-time-zones).

Also, "Irregardless" is not a word. Its just "regardless" 😉

**Comment by Dorian** [comment]
@yaauie You should probably use github's issue template: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by martinstreicher** [comment]
Is there a workaround for this?

**Comment by compwron** [comment]
Sorry. I would have used the template but I didn't really know what I was doing. I did not find a workaround. I will close this now.

**Comment by compwron** [comment]
@yaauie I thought that it would be clear enough that "behaves differently" means "gives different time results" sorry.
