### ISSUE TITLE
Enable safe_mode by default

### ISSUE THREAD

**Issue by cburgmer** [travisjeffery/timecop#154]
PR #81 added a safe mode to disable unscoped usage of timecop. As the committer stated much bad happened for them if allowing the scope-free form.

This issue is about making this behaviour the default and disallowing unscoped usage by default.

We just spend 30 dev hours on understanding flakiness introduced to our build, which finally could be narrowed down to a missing `Timecop.return` statement. The initial test runs didn't show any issues, so it was hard to narrow down the offending commit. Unrelated tests would randomly fail, initially only on the build environment, not on local machines. Rerunning those failing tests in isolation didn't show any failures, and the offending test never showed up in any of these contexts. Later the flakiness started bit by bit on developer machines affecting more and more devs.

Turning on safe_mode by default would avoid sending other teams down this rabbit hole. A following bump in the major version could communicate sufficiently that the default behaviour of timecop changed and give related users time to migrate.

Thoughts?

**Comment by ghiculescu** [comment]
+1 to this, had exactly the same thing happen to us - was caused by a `Timecop.scale` with no `Timecop.return`.
