### ISSUE TITLE
No Composer package?

### ISSUE THREAD

**Issue by gerrywastaken** [travisjeffery/timecop#156]
Hi, I'm just wondering if you are able to make this available on Packagist?

**Comment by travisjeffery** [comment]
i don't know what packagist is, looks like a php thing?

**Comment by gerrywastaken** [comment]
OMG, I'm so sorry, I was looking at your PHP clone and then posted to the wrong repository. OOPS!!!

**Comment by gerrywastaken** [comment]
I was about to close this
