### ISSUE TITLE
Not enough Jean Claude Van Damme

### ISSUE THREAD

**Issue by TheCorbin** [travisjeffery/timecop#173]
![p15984_d_v8_aa](https://cloud.githubusercontent.com/assets/8755947/12723810/a4b43f28-c8d0-11e5-80a0-d3a240225738.jpg)

**Comment by daniel-johnson** [comment]
This is totally inappropriate and off topic. I love it.

**Comment by taylorzr** [comment]
Speaking of, I made this add-on for fun: https://github.com/taylorzr/timecop-jean_claude_van_do. I don't think it's necessary, or really want to support it, or really want to flush out any more monkey-patching than I have already, but hey it works.

You can do:
```ruby
1.day.ago do
  Date.today # Whatever 1 day ago is :)
end
```

instead of:

```ruby
Timecop.travel(1.day.ago) do
  Date.today # Whatever 1 day ago is :)
end
```
