### ISSUE TITLE
Timecop.travel(1.year) flies off the rails

### ISSUE THREAD

**Issue by Epigene** [travisjeffery/timecop#174]
timecop version 0.8.0

```ruby
Time.zone.now
#=> Mon, 08 Feb 2016 14:44:40 EET +02:00
Timecop.travel(1.year)
#=> 31557600-01-01 00:00:00 +0200
```

It seems this is connected to other issues bemoaning Timecop's strange behavior regarding Intger vs. Float arguments. Calling #to_i seems to fix this.

```ruby
Timecop.travel(1.year.to_i)
#=> 2017-02-07 20:47:42 +0200
```

**Comment by travisjeffery** [comment]
Should be fixed now. Thanks!
