### ISSUE TITLE
Time freezes slightly incorrectly when using Codeship

### ISSUE THREAD

**Issue by lucascaton** [travisjeffery/timecop#176]
Hi there.

I have a spec which passes locally and fails when running in Codeship containers.
I'm not sure whether or not this problem has something to do with their containers.

This is my spec file:

``` ruby
RSpec.describe AccountDecorator do
  #...

  before { Timecop.freeze }
  after  { Timecop.return }

  it 'returns a list...' do
    expect(subject.history).to eql([
      [Time.zone.now, 10],
      [Time.zone.now, nil]
    ])
  end
end
```

This are the results:

```
Failures:

1) AccountDecorator#history returns a list...
Failure/Error:
  expected: [[2016-02-24 03:39:04.755606465 +0000, 10], [2016-02-24 03:39:04.755606465 +0000, nil]]
       got: [[2016-02-24 03:39:04.755606000 +0000, 10], [2016-02-24 03:39:04.755606000 +0000, nil]]

  (compared using eql?)
```

Any thoughts?

**Comment by lucascaton** [comment]
Hi @flomotlik, any thoughts?

**Comment by flomotlik** [comment]
A first assumption would be that the freeze somehow didn't properly trigger as the time difference is pretty small. Could you send a link to the build to our support: support@codeship.com

**Comment by lucascaton** [comment]
Thanks @flomotlik, will do.

**Comment by benoittgt** [comment]
I'm having the same issue on my own server (OVH). 

```

**Comment by benoittgt** [comment]
https://github.com/travisjeffery/timecop/issues/97#issuecomment-41294684 Fixed it.

**Comment by lucascaton** [comment]
@benoittgt awesome, it worked here. Thanks sharing the solution!

This is what I did to make it easier:

```ruby
# spec/spec_helper.rb
RSpec.configure do |config|
  # ...
  config.around(:each, freeze_time: true) do |example|
    Timecop.freeze(Time.zone.now.change(nsec: 0)) # Fixes Timecop's issue (https://goo.gl/1tujRj)
    example.run
    Timecop.return
  end
end

# spec/decorators/account_decorator_spec.rb
RSpec.describe AccountDecorator do
  describe '#history', freeze_time: true do
    #...
  end
end
```

**Comment by benoittgt** [comment]
Nice tips. Thanks
