### ISSUE TITLE
DateTime.parse does not infer time value.

### ISSUE THREAD

**Issue by KingsleyKelly** [travisjeffery/timecop#177]
Hey ! Ran in to this while running tests.

```
new_time = DateTime.now.utc + 14.days
Timecop.freeze(new_time)
DateTime.parse('Tuesday') => Tue, 22 Mar 2016 00:00:00 +0000
DateTime.parse('Tuesday 3pm') => Tue, 08 Mar 2016 15:00:00 +0000
```

I will try to provide a fix, unless this is a known issue?
Looks related to https://github.com/travisjeffery/timecop/pull/137

**Comment by JonMidhir** [comment]
Heya @KingsleyKelly, have you started work on this?

**Comment by h8is2w8** [comment]
Same problem. Any updates?
