### ISSUE TITLE
v0.8.1 tag

### ISSUE THREAD

**Issue by sanemat** [travisjeffery/timecop#180]
@travisjeffery
Would you push v0.8.1 tag to GitHub?

**Comment by sj26** [comment]
The [version file](https://github.com/travisjeffery/timecop/blob/master/lib/timecop/version.rb) doesn't seem to be correct, either.

**Comment by bquorning** [comment]
Yeah, please push both commit and tag to GitHub.

**Comment by sanemat** [comment]
@travisjeffery ping

**Comment by Zelnox** [comment]
+1

**Comment by travisjeffery** [comment]
Pushed the tag, too far back to push a commit for it. Sorry about this. This is the one time this has happened, and I will make sure it doesn't happen again.
