### ISSUE TITLE
parse_with_mock_date should be able to handle incorrect input data with clear error

### ISSUE THREAD

**Issue by pvmeerbe** [travisjeffery/timecop#188]
Currently the parse_with_mock_date routines expect the input to respond to .downcase.

However this is not always the case : imagine Form input validation with incorrect input data (for example with [dry-validation](https://github.com/dry-rb/dry-validation) and/or [dry-types](https://github.com/dry-rb/dry-types). In this case an integer value 5 could be received and an unclear error "undefined method `downcase' for 5:Fixnum" will be spawned.

Suggestion to check whether .downcase is supported for input data. This will cause the original parse function to detect the incorrect input data type and raise accordingly

**Comment by RKushnir** [comment]
Just came here for the very same reason 👍
