### ISSUE TITLE
Should Timecop.travel(nil) raise an exception like Timecop.travel("")?

### ISSUE THREAD

**Issue by mottalrd** [travisjeffery/timecop#213]
Hello, I find this behavior a bit odd

```
irb(main):001:0> require 'timecop'
=> true
irb(main):002:0> Timecop.travel(nil) do end
=> nil
irb(main):003:0> Timecop.travel("") do end
ArgumentError: no time information in ""
	from /Users/motta/.rbenv/versions/2.3.1/lib/ruby/2.3.0/time.rb:254:in `make_time'
```

shouldn't `Timecop.travel(nil)` behave in the same way as `Timecop.travel("")`?
What's the rationale for this choice? 

I got bitten by this recently :)

**Comment by andyjdavis** [comment]
This behavior seems to have changed since this issue was raised. Both nil and "" now result in an error being raised. I have raised a PR containing a test that confirms this. https://github.com/travisjeffery/timecop/pull/369
