### ISSUE TITLE
adding 0.days in Rails will make it != to time when timecop is used.

### ISSUE THREAD

**Issue by thilo** [travisjeffery/timecop#226]
in short:
`t = Time.now;
t + 0.days == t #should be true`

I created #225 with a failing test to show the problem and could use some hints to find the source of the problem with the use of Time.local in time cop.

**Comment by henrik** [comment]
Interesting! This sounds related to an issue my team's been seeing with dumping and loading from YAML. I just made a small repro for our issue, but here's a small repro for yours in the same vein:

```
> time = Time.now; time2 = time + 0.days; p [ time, time2 ].map { |x| [ x.class.name, x.to_f, x.zone ] }; time == time2
[["Time", 1553852474.7928553, "CET"], ["Time", 1553852474.7928553, "CET"]]
=> true
> Timecop.travel(Time.now) { time = Time.now; time2 = time + 0.days; p [ time, time2 ].map { |x| [ x.class.name, x.to_f, x.zone ] }; time == time2 }
[["Time", 1553852487.1235747, "CET"], ["Time", 1553852487.1235747, "CET"]]
=> false
```

So it's supposedly the same class, the same time down to the subseconds, and the same time zone. But withiin a `Timecop.travel` block, they're not considered identical for some reason. (It works fine within a `Timecop.freeze` block.)

The issue my team saw was apparently the same but going through YAML instead:

```
> Timecop.travel(Time.now) { time = Time.now; time2 = YAML.load(time.to_yaml); p [ time, time2 ].map { |x| [ x.class.name, x.to_f, x.zone ] }; time == time2 }
[["Time", 1553852634.2767212, "CET"], ["Time", 1553852634.2767212, nil]]
=> false
```

**Comment by henrik** [comment]
After further poking around, `#hash` for the times is different. That's a method commonly used for equality, typically when using a value as a hash key:

```
> Timecop.travel(Time.now) { time = Time.now; time2 = YAML.load(time.to_yaml); p [ time, time2 ].map { |x| [ x.class.name, x.to_f, x.zone, x.hash ] }; time == time2 }
[["Time", 1553852933.5511928, "CET", 1050783019138738028], ["Time", 1553852933.5511928, nil, 1259896550273451277]]
=> false
> time = Time.now; time2 = YAML.load(time.to_yaml); p [ time, time2 ].map { |x| [ x.class.name, x.to_f, x.zone, x.hash ] }; time == time2
[["Time", 1553852954.9354558, "CET", 4003415449214194444], ["Time", 1553852954.9354558, nil, 4003415449214194444]]
=> true
```

**Comment by henrik** [comment]
After still further digging, the times have different `#subsec` values. So `#to_f` and `#nsec` are the same, but `#subsec` is not:

``` ruby
> Timecop.travel(Time.now) { time = Time.now; time2 = YAML.load(time.to_yaml); p [ time, time2 ].map { |x| [ x.to_f, x.nsec, x.subsec ] }; time == time2 }
[[1553853663.704971, 704971013, (8127762421650945840106157/11529215046068469760000000)], [1553853663.704971, 704971013, (704971013/1000000000)]]
=> false
```
