### ISSUE TITLE
New gem release

### ISSUE THREAD

**Issue by dogweather** [travisjeffery/timecop#249]
The latest released gem is from 2017, 0.9.1.

**Comment by stim371** [comment]
Just ran into the Date.strptime bug that was fixed 2 years ago but not released. :)

Put a PR up to address the jruby test failures. https://github.com/travisjeffery/timecop/pull/251 Is there anything else we can help with to get 0.9.2 released?

**Comment by dkam** [comment]
Is there any timeline for a new gem release? I just came across this bug too.

**Comment by HarlemSquirrel** [comment]
```rb
Timecop.travel(next_release_date)
```

**Comment by travisjeffery** [comment]
I'll push the release by the end of the week. I'm looking to add a couple maintainers by the way.

**Comment by HarlemSquirrel** [comment]
I've used this gem for years so it's be happy to help out.

**Comment by joshuacronemeyer** [comment]
Hey all, 0.9.2 got pushed! 

Timecop.unfreeze!
