### ISSUE TITLE
Add more maintainers

### ISSUE THREAD

**Issue by sandstrom** [travisjeffery/timecop#256]
Hi @travisjeffery, thanks for an awesome gem! 🏅 

Have you considered adding more maintainers to this project?

There are a few PRs that could use some attention. Perhaps you could try enlisting some of the PR authors, or other people maintaining forks (for example @djberg96 or @nipe0324).

This gem is so great, so would love to see it get a bit more attention.

(you could retain control over gem updates for the time being, but still hand over merge access for the repo, so others can help you)

**Comment by travisjeffery** [comment]
Yeah I'd like to add a couple more maintainers.

**Comment by travisjeffery** [comment]
@djberg96 are you interested?

**Comment by sandstrom** [comment]
These two people @olleolleolle and @kachick have also submitted recent PRs and seems to be active in other ruby-related projects, based on their Github profiles. Perhaps either of them could be interested too? (but I don't know any of them)

**Comment by djberg96** [comment]
@travisjeffery I'm afraid I must pass, but thank you for considering me.

**Comment by nipe0324** [comment]
I'm interested in.

**Comment by olleolleolle** [comment]
I'd be happy to remain a Contributor, thanks for asking. You're a swell community, you all.

**Comment by joshuacronemeyer** [comment]
+1 for promoting somebody to work through some of the great pull requests that are waiting! Thanks for all your great work everyone on this thread, and PR contributors.

**Comment by joshuacronemeyer** [comment]
closing
