### ISSUE TITLE
any method to access @baseline (or actual system time)?

### ISSUE THREAD

**Issue by jpwynn** [travisjeffery/timecop#263]
Is there a method to return the current Timecop @baseline value? Or perhaps some method via Timecopy to return _actual_ system time?

This would be useful when some Rspec is logging "when" (in _actual_ time, not _timecop_ time) something occurred, for example:

```
spec_meta_logger "spec encountered FOO at #{Time.now + Timecop.whatever_timecop_offset_is}"
```

Although :baseline _is_ listed in Timecop.methods it does not seem to be accessible to inspection.

**Comment by joshuacronemeyer** [comment]
When Timecop patches ::now they keep the original ::now method as an alias called ::now_without_mock_time

**Comment by joshuacronemeyer** [comment]
Another way to do it is calling Time.now from inside a ::return block

```
2.6.1 :003 > Timecop.freeze(Time.new(1984,2,28))
 => 1984-02-28 00:00:00 -0800
2.6.1 :004 > Timecop.return { Time.now }
 => 2020-10-15 13:38:34 -0700
2.6.1 :005 > Time.now
 => 1984-02-28 00:00:00 -0800
```

**Comment by jpwynn** [comment]
excellent, thank you!
