### ISSUE TITLE
0.9.2 seemingly breaks Date.strptime just when being required

### ISSUE THREAD

**Issue by beyondcompute** [travisjeffery/timecop#271]
Hello.

Here are the steps to reproduce:

```
$ rails c
[1] pry(main)> Date.strptime('2019-07', '%Y-%m')
=> Mon, 01 Jul 2019
[2] pry(main)> require 'timecop'
=> true
[3] pry(main)> Date.strptime('2019-07', '%Y-%m')
=> Tue, 09 Jul 2019
```

`Date.strptime_without_mock_date` returns what is expected.

**Comment by beyondcompute** [comment]
I see that https://github.com/travisjeffery/timecop/pull/266 probably fixes that.

**Comment by joshuacronemeyer** [comment]
closed by https://github.com/travisjeffery/timecop/pull/266
