### ISSUE TITLE
Can we please have a new release

### ISSUE THREAD

**Issue by anklos** [travisjeffery/timecop#277]
Hey guys, any plan to have a new release? I have met an issue in the lastest release 0.9.2 and found it had been fixed 4 month ago https://github.com/travisjeffery/timecop/blame/48e0670d8f698e0dc44c10add9a7d74b6e66970c/lib/timecop/time_extensions.rb#L62

Basically it will give invalid date error by doing `Date.strptime("02/2021", '%m/%Y')` as the `mday` is 29 today, so it creates 29th Feb which is invalid adte.

Thanks

**Comment by joshuacronemeyer** [comment]
Thanks for reporting the issue and encouraging some action! 0.9.3 was released yesterday.
