### ISSUE TITLE
`Date.strptime` breaks for "Feb 2021",  "%B %Y" on the 31st of the month

### ISSUE THREAD

**Issue by paprikati** [travisjeffery/timecop#280]
If I run a spec on say 31st January, and then run `Date.strptime("Feb 2021", "%B %Y")` I get an `invalid date` error. I don't get that error for months with 31 days, so I'm assuming that is the issue.

However, if I run the same code in a rails console (i.e. without timecop wrapping it) then it works fine (I get 1 Feb 2021).

**Comment by paprikati** [comment]
Ah. I can see a comment on another issue saying it's fixed in 0.9.3. do we know when that might get released?

**Comment by paprikati** [comment]
issue originally reported at https://github.com/travisjeffery/timecop/issues/270

**Comment by joshuacronemeyer** [comment]
Thanks for reporting! 0.9.3 was released yesterday.
