### ISSUE TITLE
How to start the console?

### ISSUE THREAD

**Issue by ytkg** [travisjeffery/timecop#298]
How do I start the console when developing?  
`bundle console` is DEPRECATED.
```
$ bundle console
[DEPRECATED] bundle console will be replaced by `bin/console` generated by `bundle gem <name>`
```

If not, I would like to add the following files.
filename: `bin/console`
```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "timecop"

# You can add fixtures and/or initialization code here to make experimenting
# with your gem easier. You can also use a different console, if you like.

# (If you use this, don't forget to add pry to your Gemfile!)
# require "pry"
# Pry.start

require "irb"
IRB.start(__FILE__)
```
```
$ ./bin/console
irb(main):001:0>
```

**Comment by joshuacronemeyer** [comment]
I usually run `bundle exec irb`.

**Comment by ytkg** [comment]
Thank. After that, `require 'timecop'`?

**Comment by joshuacronemeyer** [comment]
yea, doing bundle exec irb will just make sure that the gems irb knows about are from our Gemfile.... if you need to load something particular you have to require it.  If you use bundle console and want to keep working that way feel free to add that bin.

**Comment by ytkg** [comment]
Understood.
Looks fine with `bundle exec irb`.

But using `bundle console` in Dockerfile, so I think I'll add that bin.
https://github.com/travisjeffery/timecop/blob/cce0781ab625b539d57cc86fcad7f60482501227/Dockerfile
