### ISSUE TITLE
Timecop handles GMT/UTC Time objects incorrectly

### ISSUE THREAD

**Issue by ksbek** [travisjeffery/timecop#367]
I'm wondering if this 10-year-old issue isn't fixed yet.
https://github.com/travisjeffery/timecop/issues/8

```
new_time = Time.utc(2016,10,28, 10, 24, 00)
Timecop.freeze(new_time)
t1 = Date.today.to_time.advance(days: -2)
```
t1 is **2016-10-26 00:00:00 +0100**. Why +0100 instead of +0000?

**Comment by joshuacronemeyer** [comment]
I think the bug you reference has a pretty good explanation of why things are the way they are, and someone even offered an approach for the fix. Devil is in the details though. PR would be welcome on this issue.

**Comment by ksbek** [comment]
Thanks for your reply. I'm sure the problem is with the Daylight Saving Time. I will make a PR.
