### ISSUE TITLE
Ruby 2.5 seems to work?

### ISSUE THREAD

**Issue by mick-t** [travisjeffery/timecop#383]
Hi,

I was trying to duplicate the issue you were seeing with Ruby 2.5 mentioned in [#375](https://github-redirect.dependabot.com/travisjeffery/timecop/pull/375)) to see if I could fix them as I work on a project that still uses 2.5.

My tests with a recent clone look to have succeeded:

- https://github.com/mick-t/timecop/runs/5474977578?check_suite_focus=true

I found this recent test of yours and I can't seem to duplicate it:

- https://github.com/travisjeffery/timecop/runs/4750882968?check_suite_focus=true

Maybe the issue with 2.5 was transient?

Thanks
--Mick

**Comment by joshuacronemeyer** [comment]
Happy to add it back if it works. How about a PR?

**Comment by mick-t** [comment]
Done:

https://github.com/travisjeffery/timecop/pull/384

Thanks!

**Comment by joshuacronemeyer** [comment]
@mick-t you are our ruby 2.5 champion. Have a look https://github.com/travisjeffery/timecop/actions/runs/2643024207

**Comment by mick-t** [comment]
The tests succeed in my fork:

- https://github.com/mick-t/timecop/runs/7271577936?check_suite_focus=true

I did a pull from your master branch and rebuild. I'm not sure why the difference.  Your source branch starts shows this [error](https://github.com/travisjeffery/timecop/runs/7267472346?check_suite_focus=true#step:3:37):

`  Failed to load /home/runner/.gemrc, wrong number of arguments (given 2, expected 1)`

I'm unsure as why? Will dig into it more later.
