### ISSUE TITLE
Need a proper test for making sure we don't change timezones inadvertently

### ISSUE THREAD

**Issue by joshuacronemeyer** [travisjeffery/timecop#411]
See https://github.com/travisjeffery/timecop/pull/404#issuecomment-1676559583

I think @technicalpickles is on it. :)

Our defective test is in this PR https://github.com/travisjeffery/timecop/pull/107

**Comment by alexcwatt** [comment]
Can this issue be closed? It seems like #107 added the test, unless there were more cases that need to be covered.
