### ISSUE TITLE
Timecop handles GMT/UTC Time objects incorrectly

### ISSUE THREAD

**Issue by nogweii** [travisjeffery/timecop#8]
Timecop always calls Time#getlocal regardless if the time object passed to parse_time() is GMT or UTC.

If the passed in object is an instance of Time, why not just use it's values directly? Why call getlocal? Besides, for large scale distributed applications, each machine could be in different timezones, causing getlocal to return different values! (Granted, for mocking and testing, this scenario isn't likely.)

**Comment by ksbek** [comment]
Is this fixed?
