### ISSUE TITLE
Nanoseconds drift when frozen in Rails 3.2.13 using 1.9.3-p448

### ISSUE THREAD

**Issue by cupakromer** [travisjeffery/timecop#97]
This is very similar to issue #56. However it seems to be broken with the most recent Ruby 1.9.3 patch level 1.9.3 (1.9.3-p448), Timecop (0.6.1), and Rails 3.2.13.

``` ruby
# Run this in rails console
require 'timecop'

t1 = Time.now
Timecop.freeze t1
t2 = Time.now

t1 == t2
# => false

t1.nsec == t2.nsec
# => false

t1.nsec
# => 811884000

t2.nsec
# => 811883926

Time.now == t2
# => true

Time.now.nsec
# => 811883926
```

This issue does not happen in irb or pry, only the Rails environment.

**Comment by tyre** [comment]
FWIW, seeing this on Rails 4.2.1, Timecop 0.7.3

**Comment by prurph** [comment]
Seeing with Rails 4.2.3, Timecop 0.7.4 as well.

**Comment by snex** [comment]
Rails 5.0.0.beta3, Timecop 0.8.0, seeing the problem on Travis-CI
